### ISSUE TITLE
Modification for other data structure

### ISSUE THREAD

**Issue by ban-m** [nanoporetech/pomoxis#1]
Hi.

I'm using the data from [NA12878 Human Reference on Oxford Nanopore MinION](https://github.com/nanopore-wgs-consortium/NA12878)
and I found that the replayfast5.py demo didn't work well.
The error message is below.

```
[23:14:55 - asyncio] Task exception was never retrieved
future: <Task finished coro=<replay_server() done, defined at pomoxis/provider/replayfast5.py:348> exception=KeyError("Unable to open object (Object 'intermediatedata' doesn'\
t exist)",)>
Traceback (most recent call last):
File "pomoxis/provider/replayfast5.py", line 360, in replay_server
ReplayFast5(fast5, channels, good_class=good_class, time_warp=time_warp),
File "pomoxis/provider/replayfast5.py", line 291, in __init__
for channel in self.channels
File "pomoxis/provider/replayfast5.py", line 291, in <dictcomp>
for channel in self.channels
File "pomoxis/provider/replayfast5.py", line 116, in __init__
with BulkFast5(self.fast5) as fh:
File "/home/ban-m/pomoxis/venv/lib/python3.6/site-packages/fast5_research/fast5_bulk.py", line 66, in __init__
data = self[self.__intermediate_data__]
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
File "/home/ban-m/pomoxis/venv/lib/python3.6/site-packages/h5py/_hl/group.py", line 169, in __getitem__
oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2840)
File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-s_7obrrg-build/h5py/_objects.c:2798)
File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/tmp/pip-s_7obrrg-build/h5py/h5o.c:3734)
KeyError: "Unable to open object (Object 'intermediatedata' doesn't exist)"
[23:14:55 - asyncio] Task exception was never retrieved
future: <Task finished coro=<read_until_demo.<locals>.read_until() done, defined at pomoxis/provider/replayfast5.py:397> exception=RuntimeError('yield was used instead of yie\
ld from for generator in task <Task pending coro=<read_until_demo.<locals>.read_until() running at pomoxis/provider/replayfast5.py:399>> with <generator object replay_client \
at 0x7f48c02f9e08>',)>
Traceback (most recent call last):
File "pomoxis/provider/replayfast5.py", line 399, in read_until
client = yield replay_client(port)
RuntimeError: yield was used instead of yield from for generator in task <Task pending coro=<read_until_demo.<locals>.read_until() running at pomoxis/provider/replayfast5.py:\
399>> with <generator object replay_client at 0x7f48c02f9e08>
```

There seems to be some problem in fast5_bulk.py.
In that script, the group named '/IntermediateData/'
was required but there's no such group in the data above.
Also,there are other fields not existing in that .fast5 file(such as '/Meta/'group).
So, Could you let me know how can I handle it? Thank you.

**Comment by cjw85** [comment]
Hi @ban-m,

The functionality expects a variant of .fast5 we call a "bulk fast5 file". These are an optional output of MinKnow which contains the signal data for all channels of a ONT device (including periods of time where a channel is not undergoing an strand translocation. Outputting a bulk fast5 can be configured when the user starts and experiment in MinKnow.

I apologize for any confusion, we will make the documentation more explicit with respect to this issue.

**Comment by ban-m** [comment]
Hi cjw85
I probably understand where i went wrong and  how to manage it.
Thank you!
